//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRService.ReportServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://creditws.les.com/", ConfigurationName="ReportServiceReference.ReportService")]
    public interface ReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getZrrxyxxList(string RequestUser, string RequestPwd, string Xm, string Sfzjhm, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getZrrxyxxListAsync(string RequestUser, string RequestPwd, string Xm, string Sfzjhm, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getZrrxyxx(string RequestUser, string RequestPwd, string Grid, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getZrrxyxxAsync(string RequestUser, string RequestPwd, string Grid, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getQyxyxx(string RequestUser, string RequestPwd, string qymc, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getQyxyxxAsync(string RequestUser, string RequestPwd, string qymc, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getreport(string RequestUser, string RequestPwd, string Reportid, string Tyshxydm, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getreportAsync(string RequestUser, string RequestPwd, string Reportid, string Tyshxydm, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getreportlist(string RequestUser, string RequestPwd, string Sfzjhm, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getreportlistAsync(string RequestUser, string RequestPwd, string Sfzjhm, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getQyjbxx(string RequestUser, string RequestPwd, string qyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getQyjbxxAsync(string RequestUser, string RequestPwd, string qyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string checkXybgByYzm(string RequestUser, string RequestPwd, string Yzm, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> checkXybgByYzmAsync(string RequestUser, string RequestPwd, string Yzm, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string updatereportstatus(string RequestUser, string RequestPwd, string Reportid, string CapturedImg, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> updatereportstatusAsync(string RequestUser, string RequestPwd, string Reportid, string CapturedImg, string Type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportServiceChannel : ECRService.ReportServiceReference.ReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<ECRService.ReportServiceReference.ReportService>, ECRService.ReportServiceReference.ReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getZrrxyxxList(string RequestUser, string RequestPwd, string Xm, string Sfzjhm, string Type) {
            return base.Channel.getZrrxyxxList(RequestUser, RequestPwd, Xm, Sfzjhm, Type);
        }
        
        public System.Threading.Tasks.Task<string> getZrrxyxxListAsync(string RequestUser, string RequestPwd, string Xm, string Sfzjhm, string Type) {
            return base.Channel.getZrrxyxxListAsync(RequestUser, RequestPwd, Xm, Sfzjhm, Type);
        }
        
        public string getZrrxyxx(string RequestUser, string RequestPwd, string Grid, string Type) {
            return base.Channel.getZrrxyxx(RequestUser, RequestPwd, Grid, Type);
        }
        
        public System.Threading.Tasks.Task<string> getZrrxyxxAsync(string RequestUser, string RequestPwd, string Grid, string Type) {
            return base.Channel.getZrrxyxxAsync(RequestUser, RequestPwd, Grid, Type);
        }
        
        public string getQyxyxx(string RequestUser, string RequestPwd, string qymc, string Type) {
            return base.Channel.getQyxyxx(RequestUser, RequestPwd, qymc, Type);
        }
        
        public System.Threading.Tasks.Task<string> getQyxyxxAsync(string RequestUser, string RequestPwd, string qymc, string Type) {
            return base.Channel.getQyxyxxAsync(RequestUser, RequestPwd, qymc, Type);
        }
        
        public string getreport(string RequestUser, string RequestPwd, string Reportid, string Tyshxydm, string Type) {
            return base.Channel.getreport(RequestUser, RequestPwd, Reportid, Tyshxydm, Type);
        }
        
        public System.Threading.Tasks.Task<string> getreportAsync(string RequestUser, string RequestPwd, string Reportid, string Tyshxydm, string Type) {
            return base.Channel.getreportAsync(RequestUser, RequestPwd, Reportid, Tyshxydm, Type);
        }
        
        public string getreportlist(string RequestUser, string RequestPwd, string Sfzjhm, string Type) {
            return base.Channel.getreportlist(RequestUser, RequestPwd, Sfzjhm, Type);
        }
        
        public System.Threading.Tasks.Task<string> getreportlistAsync(string RequestUser, string RequestPwd, string Sfzjhm, string Type) {
            return base.Channel.getreportlistAsync(RequestUser, RequestPwd, Sfzjhm, Type);
        }
        
        public string getQyjbxx(string RequestUser, string RequestPwd, string qyid) {
            return base.Channel.getQyjbxx(RequestUser, RequestPwd, qyid);
        }
        
        public System.Threading.Tasks.Task<string> getQyjbxxAsync(string RequestUser, string RequestPwd, string qyid) {
            return base.Channel.getQyjbxxAsync(RequestUser, RequestPwd, qyid);
        }
        
        public string checkXybgByYzm(string RequestUser, string RequestPwd, string Yzm, string Type) {
            return base.Channel.checkXybgByYzm(RequestUser, RequestPwd, Yzm, Type);
        }
        
        public System.Threading.Tasks.Task<string> checkXybgByYzmAsync(string RequestUser, string RequestPwd, string Yzm, string Type) {
            return base.Channel.checkXybgByYzmAsync(RequestUser, RequestPwd, Yzm, Type);
        }
        
        public string updatereportstatus(string RequestUser, string RequestPwd, string Reportid, string CapturedImg, string Type) {
            return base.Channel.updatereportstatus(RequestUser, RequestPwd, Reportid, CapturedImg, Type);
        }
        
        public System.Threading.Tasks.Task<string> updatereportstatusAsync(string RequestUser, string RequestPwd, string Reportid, string CapturedImg, string Type) {
            return base.Channel.updatereportstatusAsync(RequestUser, RequestPwd, Reportid, CapturedImg, Type);
        }
    }
}
