//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXC.ServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class getreporttemplateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jxCommonResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jxCommonResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class jxCommonResponse : webserviceResponse {
        
        private jxCommonResponseEntry[] detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public jxCommonResponseEntry[] detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class jxCommonResponseEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jxCommonResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class webserviceResponse : serialize {
        
        private string developerMessageField;
        
        private string messageField;
        
        private string messageCodeField;
        
        private string publicKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string developerMessage {
            get {
                return this.developerMessageField;
            }
            set {
                this.developerMessageField = value;
                this.RaisePropertyChanged("developerMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string messageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("messageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string publicKey {
            get {
                return this.publicKeyField;
            }
            set {
                this.publicKeyField = value;
                this.RaisePropertyChanged("publicKey");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(webserviceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jxCommonResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(webserviceRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jxCommonRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class serialize : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jxCommonRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class webserviceRequest : serialize {
        
        private byte[] ciphertextField;
        
        private string clientTypeField;
        
        private string deviceCodeField;
        
        private string modulepasswordField;
        
        private string moduleusernameField;
        
        private string publicKeyField;
        
        private string requestMethodField;
        
        private string requestUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] ciphertext {
            get {
                return this.ciphertextField;
            }
            set {
                this.ciphertextField = value;
                this.RaisePropertyChanged("ciphertext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clientType {
            get {
                return this.clientTypeField;
            }
            set {
                this.clientTypeField = value;
                this.RaisePropertyChanged("clientType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string deviceCode {
            get {
                return this.deviceCodeField;
            }
            set {
                this.deviceCodeField = value;
                this.RaisePropertyChanged("deviceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string modulepassword {
            get {
                return this.modulepasswordField;
            }
            set {
                this.modulepasswordField = value;
                this.RaisePropertyChanged("modulepassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string moduleusername {
            get {
                return this.moduleusernameField;
            }
            set {
                this.moduleusernameField = value;
                this.RaisePropertyChanged("moduleusername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string publicKey {
            get {
                return this.publicKeyField;
            }
            set {
                this.publicKeyField = value;
                this.RaisePropertyChanged("publicKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string requestMethod {
            get {
                return this.requestMethodField;
            }
            set {
                this.requestMethodField = value;
                this.RaisePropertyChanged("requestMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string requestUrl {
            get {
                return this.requestUrlField;
            }
            set {
                this.requestUrlField = value;
                this.RaisePropertyChanged("requestUrl");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class jxCommonRequest : webserviceRequest {
        
        private string jsonStringParamsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string jsonStringParams {
            get {
                return this.jsonStringParamsField;
            }
            set {
                this.jsonStringParamsField = value;
                this.RaisePropertyChanged("jsonStringParams");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class getreporttemplate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jxCommonRequest arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jxCommonRequest arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class getpersoninfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jxCommonResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jxCommonResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class getpersoninfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jxCommonRequest arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jxCommonRequest arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class getLegalPersonPageResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jxCommonResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jxCommonResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class getLegalPersonPage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jxCommonRequest arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jxCommonRequest arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class exportpersonalpdfResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jxCommonResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jxCommonResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class exportpersonalpdf : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jxCommonRequest arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jxCommonRequest arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jsonObject))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public abstract partial class json : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class jsonObject : json {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class exportlegalpersonalpdfResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jxCommonResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jxCommonResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/")]
    public partial class exportlegalpersonalpdf : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jxCommonRequest arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jxCommonRequest arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", ConfigurationName="ServiceReference.CreditReport")]
    public interface CreditReport {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EXC.ServiceReference.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getreporttemplateResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getreporttemplate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getpersoninfoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getpersoninfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getLegalPersonPageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getLegalPersonPage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportpersonalpdfResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportpersonalpdf))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(json))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportlegalpersonalpdfResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportlegalpersonalpdf))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serialize))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EXC.ServiceReference.exportlegalpersonalpdfResponse1 exportlegalpersonalpdf(EXC.ServiceReference.exportlegalpersonalpdf1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EXC.ServiceReference.exportlegalpersonalpdfResponse1> exportlegalpersonalpdfAsync(EXC.ServiceReference.exportlegalpersonalpdf1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EXC.ServiceReference.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getreporttemplateResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getreporttemplate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getpersoninfoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getpersoninfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getLegalPersonPageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getLegalPersonPage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportpersonalpdfResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportpersonalpdf))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(json))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportlegalpersonalpdfResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportlegalpersonalpdf))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serialize))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EXC.ServiceReference.exportpersonalpdfResponse1 exportpersonalpdf(EXC.ServiceReference.exportpersonalpdf1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EXC.ServiceReference.exportpersonalpdfResponse1> exportpersonalpdfAsync(EXC.ServiceReference.exportpersonalpdf1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getreporttemplateResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getreporttemplate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getpersoninfoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getpersoninfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getLegalPersonPageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getLegalPersonPage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportpersonalpdfResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportpersonalpdf))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(json))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportlegalpersonalpdfResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportlegalpersonalpdf))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serialize))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EXC.ServiceReference.getLegalPersonPageResponse1 getLegalPersonPage(EXC.ServiceReference.getLegalPersonPage1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EXC.ServiceReference.getLegalPersonPageResponse1> getLegalPersonPageAsync(EXC.ServiceReference.getLegalPersonPage1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getreporttemplateResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getreporttemplate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getpersoninfoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getpersoninfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getLegalPersonPageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getLegalPersonPage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportpersonalpdfResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportpersonalpdf))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(json))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportlegalpersonalpdfResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportlegalpersonalpdf))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serialize))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EXC.ServiceReference.getpersoninfoResponse1 getpersoninfo(EXC.ServiceReference.getpersoninfo1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EXC.ServiceReference.getpersoninfoResponse1> getpersoninfoAsync(EXC.ServiceReference.getpersoninfo1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getreporttemplateResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getreporttemplate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getpersoninfoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getpersoninfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getLegalPersonPageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getLegalPersonPage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportpersonalpdfResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportpersonalpdf))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(json))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportlegalpersonalpdfResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exportlegalpersonalpdf))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serialize))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EXC.ServiceReference.getreporttemplateResponse1 getreporttemplate(EXC.ServiceReference.getreporttemplate1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EXC.ServiceReference.getreporttemplateResponse1> getreporttemplateAsync(EXC.ServiceReference.getreporttemplate1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportlegalpersonalpdf", WrapperNamespace="http://provider.portal.webservice.credit.lnlic.com/", IsWrapped=true)]
    public partial class exportlegalpersonalpdf1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EXC.ServiceReference.jxCommonRequest arg0;
        
        public exportlegalpersonalpdf1() {
        }
        
        public exportlegalpersonalpdf1(EXC.ServiceReference.jxCommonRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportlegalpersonalpdfResponse", WrapperNamespace="http://provider.portal.webservice.credit.lnlic.com/", IsWrapped=true)]
    public partial class exportlegalpersonalpdfResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EXC.ServiceReference.jxCommonResponse @return;
        
        public exportlegalpersonalpdfResponse1() {
        }
        
        public exportlegalpersonalpdfResponse1(EXC.ServiceReference.jxCommonResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportpersonalpdf", WrapperNamespace="http://provider.portal.webservice.credit.lnlic.com/", IsWrapped=true)]
    public partial class exportpersonalpdf1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EXC.ServiceReference.jxCommonRequest arg0;
        
        public exportpersonalpdf1() {
        }
        
        public exportpersonalpdf1(EXC.ServiceReference.jxCommonRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportpersonalpdfResponse", WrapperNamespace="http://provider.portal.webservice.credit.lnlic.com/", IsWrapped=true)]
    public partial class exportpersonalpdfResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EXC.ServiceReference.jxCommonResponse @return;
        
        public exportpersonalpdfResponse1() {
        }
        
        public exportpersonalpdfResponse1(EXC.ServiceReference.jxCommonResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLegalPersonPage", WrapperNamespace="http://provider.portal.webservice.credit.lnlic.com/", IsWrapped=true)]
    public partial class getLegalPersonPage1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EXC.ServiceReference.jxCommonRequest arg0;
        
        public getLegalPersonPage1() {
        }
        
        public getLegalPersonPage1(EXC.ServiceReference.jxCommonRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLegalPersonPageResponse", WrapperNamespace="http://provider.portal.webservice.credit.lnlic.com/", IsWrapped=true)]
    public partial class getLegalPersonPageResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EXC.ServiceReference.jxCommonResponse @return;
        
        public getLegalPersonPageResponse1() {
        }
        
        public getLegalPersonPageResponse1(EXC.ServiceReference.jxCommonResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getpersoninfo", WrapperNamespace="http://provider.portal.webservice.credit.lnlic.com/", IsWrapped=true)]
    public partial class getpersoninfo1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EXC.ServiceReference.jxCommonRequest arg0;
        
        public getpersoninfo1() {
        }
        
        public getpersoninfo1(EXC.ServiceReference.jxCommonRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getpersoninfoResponse", WrapperNamespace="http://provider.portal.webservice.credit.lnlic.com/", IsWrapped=true)]
    public partial class getpersoninfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EXC.ServiceReference.jxCommonResponse @return;
        
        public getpersoninfoResponse1() {
        }
        
        public getpersoninfoResponse1(EXC.ServiceReference.jxCommonResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getreporttemplate", WrapperNamespace="http://provider.portal.webservice.credit.lnlic.com/", IsWrapped=true)]
    public partial class getreporttemplate1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EXC.ServiceReference.jxCommonRequest arg0;
        
        public getreporttemplate1() {
        }
        
        public getreporttemplate1(EXC.ServiceReference.jxCommonRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getreporttemplateResponse", WrapperNamespace="http://provider.portal.webservice.credit.lnlic.com/", IsWrapped=true)]
    public partial class getreporttemplateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.portal.webservice.credit.lnlic.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EXC.ServiceReference.jxCommonResponse @return;
        
        public getreporttemplateResponse1() {
        }
        
        public getreporttemplateResponse1(EXC.ServiceReference.jxCommonResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreditReportChannel : EXC.ServiceReference.CreditReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditReportClient : System.ServiceModel.ClientBase<EXC.ServiceReference.CreditReport>, EXC.ServiceReference.CreditReport {
        
        public CreditReportClient() {
        }
        
        public CreditReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EXC.ServiceReference.exportlegalpersonalpdfResponse1 EXC.ServiceReference.CreditReport.exportlegalpersonalpdf(EXC.ServiceReference.exportlegalpersonalpdf1 request) {
            return base.Channel.exportlegalpersonalpdf(request);
        }
        
        public EXC.ServiceReference.jxCommonResponse exportlegalpersonalpdf(EXC.ServiceReference.jxCommonRequest arg0) {
            EXC.ServiceReference.exportlegalpersonalpdf1 inValue = new EXC.ServiceReference.exportlegalpersonalpdf1();
            inValue.arg0 = arg0;
            EXC.ServiceReference.exportlegalpersonalpdfResponse1 retVal = ((EXC.ServiceReference.CreditReport)(this)).exportlegalpersonalpdf(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXC.ServiceReference.exportlegalpersonalpdfResponse1> EXC.ServiceReference.CreditReport.exportlegalpersonalpdfAsync(EXC.ServiceReference.exportlegalpersonalpdf1 request) {
            return base.Channel.exportlegalpersonalpdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXC.ServiceReference.exportlegalpersonalpdfResponse1> exportlegalpersonalpdfAsync(EXC.ServiceReference.jxCommonRequest arg0) {
            EXC.ServiceReference.exportlegalpersonalpdf1 inValue = new EXC.ServiceReference.exportlegalpersonalpdf1();
            inValue.arg0 = arg0;
            return ((EXC.ServiceReference.CreditReport)(this)).exportlegalpersonalpdfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EXC.ServiceReference.exportpersonalpdfResponse1 EXC.ServiceReference.CreditReport.exportpersonalpdf(EXC.ServiceReference.exportpersonalpdf1 request) {
            return base.Channel.exportpersonalpdf(request);
        }
        
        public EXC.ServiceReference.jxCommonResponse exportpersonalpdf(EXC.ServiceReference.jxCommonRequest arg0) {
            EXC.ServiceReference.exportpersonalpdf1 inValue = new EXC.ServiceReference.exportpersonalpdf1();
            inValue.arg0 = arg0;
            EXC.ServiceReference.exportpersonalpdfResponse1 retVal = ((EXC.ServiceReference.CreditReport)(this)).exportpersonalpdf(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXC.ServiceReference.exportpersonalpdfResponse1> EXC.ServiceReference.CreditReport.exportpersonalpdfAsync(EXC.ServiceReference.exportpersonalpdf1 request) {
            return base.Channel.exportpersonalpdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXC.ServiceReference.exportpersonalpdfResponse1> exportpersonalpdfAsync(EXC.ServiceReference.jxCommonRequest arg0) {
            EXC.ServiceReference.exportpersonalpdf1 inValue = new EXC.ServiceReference.exportpersonalpdf1();
            inValue.arg0 = arg0;
            return ((EXC.ServiceReference.CreditReport)(this)).exportpersonalpdfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EXC.ServiceReference.getLegalPersonPageResponse1 EXC.ServiceReference.CreditReport.getLegalPersonPage(EXC.ServiceReference.getLegalPersonPage1 request) {
            return base.Channel.getLegalPersonPage(request);
        }
        
        public EXC.ServiceReference.jxCommonResponse getLegalPersonPage(EXC.ServiceReference.jxCommonRequest arg0) {
            EXC.ServiceReference.getLegalPersonPage1 inValue = new EXC.ServiceReference.getLegalPersonPage1();
            inValue.arg0 = arg0;
            EXC.ServiceReference.getLegalPersonPageResponse1 retVal = ((EXC.ServiceReference.CreditReport)(this)).getLegalPersonPage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXC.ServiceReference.getLegalPersonPageResponse1> EXC.ServiceReference.CreditReport.getLegalPersonPageAsync(EXC.ServiceReference.getLegalPersonPage1 request) {
            return base.Channel.getLegalPersonPageAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXC.ServiceReference.getLegalPersonPageResponse1> getLegalPersonPageAsync(EXC.ServiceReference.jxCommonRequest arg0) {
            EXC.ServiceReference.getLegalPersonPage1 inValue = new EXC.ServiceReference.getLegalPersonPage1();
            inValue.arg0 = arg0;
            return ((EXC.ServiceReference.CreditReport)(this)).getLegalPersonPageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EXC.ServiceReference.getpersoninfoResponse1 EXC.ServiceReference.CreditReport.getpersoninfo(EXC.ServiceReference.getpersoninfo1 request) {
            return base.Channel.getpersoninfo(request);
        }
        
        public EXC.ServiceReference.jxCommonResponse getpersoninfo(EXC.ServiceReference.jxCommonRequest arg0) {
            EXC.ServiceReference.getpersoninfo1 inValue = new EXC.ServiceReference.getpersoninfo1();
            inValue.arg0 = arg0;
            EXC.ServiceReference.getpersoninfoResponse1 retVal = ((EXC.ServiceReference.CreditReport)(this)).getpersoninfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXC.ServiceReference.getpersoninfoResponse1> EXC.ServiceReference.CreditReport.getpersoninfoAsync(EXC.ServiceReference.getpersoninfo1 request) {
            return base.Channel.getpersoninfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXC.ServiceReference.getpersoninfoResponse1> getpersoninfoAsync(EXC.ServiceReference.jxCommonRequest arg0) {
            EXC.ServiceReference.getpersoninfo1 inValue = new EXC.ServiceReference.getpersoninfo1();
            inValue.arg0 = arg0;
            return ((EXC.ServiceReference.CreditReport)(this)).getpersoninfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EXC.ServiceReference.getreporttemplateResponse1 EXC.ServiceReference.CreditReport.getreporttemplate(EXC.ServiceReference.getreporttemplate1 request) {
            return base.Channel.getreporttemplate(request);
        }
        
        public EXC.ServiceReference.jxCommonResponse getreporttemplate(EXC.ServiceReference.jxCommonRequest arg0) {
            EXC.ServiceReference.getreporttemplate1 inValue = new EXC.ServiceReference.getreporttemplate1();
            inValue.arg0 = arg0;
            EXC.ServiceReference.getreporttemplateResponse1 retVal = ((EXC.ServiceReference.CreditReport)(this)).getreporttemplate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXC.ServiceReference.getreporttemplateResponse1> EXC.ServiceReference.CreditReport.getreporttemplateAsync(EXC.ServiceReference.getreporttemplate1 request) {
            return base.Channel.getreporttemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXC.ServiceReference.getreporttemplateResponse1> getreporttemplateAsync(EXC.ServiceReference.jxCommonRequest arg0) {
            EXC.ServiceReference.getreporttemplate1 inValue = new EXC.ServiceReference.getreporttemplate1();
            inValue.arg0 = arg0;
            return ((EXC.ServiceReference.CreditReport)(this)).getreporttemplateAsync(inValue);
        }
    }
}
