//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXC.QingDao1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QingDao1.FRReportToBase64Soap")]
    public interface FRReportToBase64Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 csResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cs", ReplyAction="*")]
        EXC.QingDao1.csResponse cs(EXC.QingDao1.csRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cs", ReplyAction="*")]
        System.Threading.Tasks.Task<EXC.QingDao1.csResponse> csAsync(EXC.QingDao1.csRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 apikey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport", ReplyAction="*")]
        EXC.QingDao1.GetReportResponse GetReport(EXC.QingDao1.GetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport", ReplyAction="*")]
        System.Threading.Tasks.Task<EXC.QingDao1.GetReportResponse> GetReportAsync(EXC.QingDao1.GetReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class csRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cs", Namespace="http://tempuri.org/", Order=0)]
        public EXC.QingDao1.csRequestBody Body;
        
        public csRequest() {
        }
        
        public csRequest(EXC.QingDao1.csRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class csRequestBody {
        
        public csRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class csResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="csResponse", Namespace="http://tempuri.org/", Order=0)]
        public EXC.QingDao1.csResponseBody Body;
        
        public csResponse() {
        }
        
        public csResponse(EXC.QingDao1.csResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class csResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string csResult;
        
        public csResponseBody() {
        }
        
        public csResponseBody(string csResult) {
            this.csResult = csResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReport", Namespace="http://tempuri.org/", Order=0)]
        public EXC.QingDao1.GetReportRequestBody Body;
        
        public GetReportRequest() {
        }
        
        public GetReportRequest(EXC.QingDao1.GetReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apikey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dm;
        
        public GetReportRequestBody() {
        }
        
        public GetReportRequestBody(string apikey, string mc, string dm) {
            this.apikey = apikey;
            this.mc = mc;
            this.dm = dm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public EXC.QingDao1.GetReportResponseBody Body;
        
        public GetReportResponse() {
        }
        
        public GetReportResponse(EXC.QingDao1.GetReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetReportResult;
        
        public GetReportResponseBody() {
        }
        
        public GetReportResponseBody(string GetReportResult) {
            this.GetReportResult = GetReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRReportToBase64SoapChannel : EXC.QingDao1.FRReportToBase64Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRReportToBase64SoapClient : System.ServiceModel.ClientBase<EXC.QingDao1.FRReportToBase64Soap>, EXC.QingDao1.FRReportToBase64Soap {
        
        public FRReportToBase64SoapClient() {
        }
        
        public FRReportToBase64SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRReportToBase64SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRReportToBase64SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRReportToBase64SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EXC.QingDao1.csResponse EXC.QingDao1.FRReportToBase64Soap.cs(EXC.QingDao1.csRequest request) {
            return base.Channel.cs(request);
        }
        
        public string cs() {
            EXC.QingDao1.csRequest inValue = new EXC.QingDao1.csRequest();
            inValue.Body = new EXC.QingDao1.csRequestBody();
            EXC.QingDao1.csResponse retVal = ((EXC.QingDao1.FRReportToBase64Soap)(this)).cs(inValue);
            return retVal.Body.csResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXC.QingDao1.csResponse> EXC.QingDao1.FRReportToBase64Soap.csAsync(EXC.QingDao1.csRequest request) {
            return base.Channel.csAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXC.QingDao1.csResponse> csAsync() {
            EXC.QingDao1.csRequest inValue = new EXC.QingDao1.csRequest();
            inValue.Body = new EXC.QingDao1.csRequestBody();
            return ((EXC.QingDao1.FRReportToBase64Soap)(this)).csAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EXC.QingDao1.GetReportResponse EXC.QingDao1.FRReportToBase64Soap.GetReport(EXC.QingDao1.GetReportRequest request) {
            return base.Channel.GetReport(request);
        }
        
        public string GetReport(string apikey, string mc, string dm) {
            EXC.QingDao1.GetReportRequest inValue = new EXC.QingDao1.GetReportRequest();
            inValue.Body = new EXC.QingDao1.GetReportRequestBody();
            inValue.Body.apikey = apikey;
            inValue.Body.mc = mc;
            inValue.Body.dm = dm;
            EXC.QingDao1.GetReportResponse retVal = ((EXC.QingDao1.FRReportToBase64Soap)(this)).GetReport(inValue);
            return retVal.Body.GetReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EXC.QingDao1.GetReportResponse> EXC.QingDao1.FRReportToBase64Soap.GetReportAsync(EXC.QingDao1.GetReportRequest request) {
            return base.Channel.GetReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<EXC.QingDao1.GetReportResponse> GetReportAsync(string apikey, string mc, string dm) {
            EXC.QingDao1.GetReportRequest inValue = new EXC.QingDao1.GetReportRequest();
            inValue.Body = new EXC.QingDao1.GetReportRequestBody();
            inValue.Body.apikey = apikey;
            inValue.Body.mc = mc;
            inValue.Body.dm = dm;
            return ((EXC.QingDao1.FRReportToBase64Soap)(this)).GetReportAsync(inValue);
        }
    }
}
