//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.QingDaoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QingDaoServiceReference.FRReportToBase64Soap")]
    public interface FRReportToBase64Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 csResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cs", ReplyAction="*")]
        Resources.QingDaoServiceReference.csResponse cs(Resources.QingDaoServiceReference.csRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cs", ReplyAction="*")]
        System.Threading.Tasks.Task<Resources.QingDaoServiceReference.csResponse> csAsync(Resources.QingDaoServiceReference.csRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 apikey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport", ReplyAction="*")]
        Resources.QingDaoServiceReference.GetReportResponse GetReport(Resources.QingDaoServiceReference.GetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport", ReplyAction="*")]
        System.Threading.Tasks.Task<Resources.QingDaoServiceReference.GetReportResponse> GetReportAsync(Resources.QingDaoServiceReference.GetReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class csRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cs", Namespace="http://tempuri.org/", Order=0)]
        public Resources.QingDaoServiceReference.csRequestBody Body;
        
        public csRequest() {
        }
        
        public csRequest(Resources.QingDaoServiceReference.csRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class csRequestBody {
        
        public csRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class csResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="csResponse", Namespace="http://tempuri.org/", Order=0)]
        public Resources.QingDaoServiceReference.csResponseBody Body;
        
        public csResponse() {
        }
        
        public csResponse(Resources.QingDaoServiceReference.csResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class csResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string csResult;
        
        public csResponseBody() {
        }
        
        public csResponseBody(string csResult) {
            this.csResult = csResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReport", Namespace="http://tempuri.org/", Order=0)]
        public Resources.QingDaoServiceReference.GetReportRequestBody Body;
        
        public GetReportRequest() {
        }
        
        public GetReportRequest(Resources.QingDaoServiceReference.GetReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apikey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dm;
        
        public GetReportRequestBody() {
        }
        
        public GetReportRequestBody(string apikey, string mc, string dm) {
            this.apikey = apikey;
            this.mc = mc;
            this.dm = dm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public Resources.QingDaoServiceReference.GetReportResponseBody Body;
        
        public GetReportResponse() {
        }
        
        public GetReportResponse(Resources.QingDaoServiceReference.GetReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetReportResult;
        
        public GetReportResponseBody() {
        }
        
        public GetReportResponseBody(string GetReportResult) {
            this.GetReportResult = GetReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FRReportToBase64SoapChannel : Resources.QingDaoServiceReference.FRReportToBase64Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FRReportToBase64SoapClient : System.ServiceModel.ClientBase<Resources.QingDaoServiceReference.FRReportToBase64Soap>, Resources.QingDaoServiceReference.FRReportToBase64Soap {
        
        public FRReportToBase64SoapClient() {
        }
        
        public FRReportToBase64SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FRReportToBase64SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRReportToBase64SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FRReportToBase64SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Resources.QingDaoServiceReference.csResponse Resources.QingDaoServiceReference.FRReportToBase64Soap.cs(Resources.QingDaoServiceReference.csRequest request) {
            return base.Channel.cs(request);
        }
        
        public string cs() {
            Resources.QingDaoServiceReference.csRequest inValue = new Resources.QingDaoServiceReference.csRequest();
            inValue.Body = new Resources.QingDaoServiceReference.csRequestBody();
            Resources.QingDaoServiceReference.csResponse retVal = ((Resources.QingDaoServiceReference.FRReportToBase64Soap)(this)).cs(inValue);
            return retVal.Body.csResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Resources.QingDaoServiceReference.csResponse> Resources.QingDaoServiceReference.FRReportToBase64Soap.csAsync(Resources.QingDaoServiceReference.csRequest request) {
            return base.Channel.csAsync(request);
        }
        
        public System.Threading.Tasks.Task<Resources.QingDaoServiceReference.csResponse> csAsync() {
            Resources.QingDaoServiceReference.csRequest inValue = new Resources.QingDaoServiceReference.csRequest();
            inValue.Body = new Resources.QingDaoServiceReference.csRequestBody();
            return ((Resources.QingDaoServiceReference.FRReportToBase64Soap)(this)).csAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Resources.QingDaoServiceReference.GetReportResponse Resources.QingDaoServiceReference.FRReportToBase64Soap.GetReport(Resources.QingDaoServiceReference.GetReportRequest request) {
            return base.Channel.GetReport(request);
        }
        
        public string GetReport(string apikey, string mc, string dm) {
            Resources.QingDaoServiceReference.GetReportRequest inValue = new Resources.QingDaoServiceReference.GetReportRequest();
            inValue.Body = new Resources.QingDaoServiceReference.GetReportRequestBody();
            inValue.Body.apikey = apikey;
            inValue.Body.mc = mc;
            inValue.Body.dm = dm;
            Resources.QingDaoServiceReference.GetReportResponse retVal = ((Resources.QingDaoServiceReference.FRReportToBase64Soap)(this)).GetReport(inValue);
            return retVal.Body.GetReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Resources.QingDaoServiceReference.GetReportResponse> Resources.QingDaoServiceReference.FRReportToBase64Soap.GetReportAsync(Resources.QingDaoServiceReference.GetReportRequest request) {
            return base.Channel.GetReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Resources.QingDaoServiceReference.GetReportResponse> GetReportAsync(string apikey, string mc, string dm) {
            Resources.QingDaoServiceReference.GetReportRequest inValue = new Resources.QingDaoServiceReference.GetReportRequest();
            inValue.Body = new Resources.QingDaoServiceReference.GetReportRequestBody();
            inValue.Body.apikey = apikey;
            inValue.Body.mc = mc;
            inValue.Body.dm = dm;
            return ((Resources.QingDaoServiceReference.FRReportToBase64Soap)(this)).GetReportAsync(inValue);
        }
    }
}
